# Generated by Django 2.1.4 on 2018-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
