# Generated by Django 2.1.4 on 2019-01-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_dairy_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dairy',
            new_name='Diary',
        ),
    ]
