# Generated by Django 2.1.4 on 2019-02-02 06:37

import diary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=diary.models.user_directory_path)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='diary.Diary')),
            ],
        ),
    ]
